import type { ExerciseDefinition } from './models.ts';

export const EXERCISES: ExerciseDefinition[] = [
  { id: 'bike_easy_spin', version: 1, name: 'Easy Spin', modality: 'cycling', movementPatterns: ['cyclical'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_knee_pain'], instruction: 'Use a smooth cadence and conversational breathing. Finish unchanged or fresher.' },
  { id: 'bike_progressive_warmup', version: 1, name: 'Progressive Bike Warm-up', modality: 'cycling', movementPatterns: ['cyclical'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_knee_pain'], instruction: 'Increase pressure gradually without turning the warm-up into a test.' },
  { id: 'bike_cadence_activation', version: 1, name: 'Cadence Activation', modality: 'cycling', movementPatterns: ['cyclical'], primaryMuscles: ['hip_flexors', 'quadriceps', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: [], instruction: 'Increase cadence while keeping the upper body quiet and power controlled.' },
  { id: 'bike_threshold_interval', version: 1, name: 'Threshold Interval', modality: 'cycling', movementPatterns: ['cyclical'], primaryMuscles: ['quadriceps', 'glutes'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_knee_pain'], instruction: 'Ride repeatably. The final interval should resemble the first rather than becoming a maximal test.' },
  { id: 'bike_over_under_interval', version: 1, name: 'Over-under Interval', modality: 'cycling', movementPatterns: ['cyclical'], primaryMuscles: ['quadriceps', 'glutes'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Alternate controlled surges with meaningful pedalling recovery near sustainable power.' },
  { id: 'bike_short_surge', version: 1, name: 'Short Cycling Surge', modality: 'cycling', movementPatterns: ['cyclical', 'acceleration'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Accelerate decisively, then return to controlled pedalling instead of coasting completely.' },
  { id: 'bike_hard_finish', version: 1, name: 'Fatigue-resistant Hard Finish', modality: 'cycling', movementPatterns: ['cyclical', 'sustained_power'], primaryMuscles: ['quadriceps', 'glutes'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Produce a strong final effort after accumulated work while preserving cadence and position.' },
  { id: 'hang_power_clean', version: 1, name: 'Hang Power Clean', modality: 'strength', movementPatterns: ['hinge', 'triple_extension', 'pull'], primaryMuscles: ['glutes', 'hamstrings', 'traps'], equipment: ['barbell'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'high', contraindicationTags: ['acute_knee_pain', 'reactive_achilles'], instruction: 'Use light-to-moderate loads and crisp speed. Stop before bar speed drops.' },
  { id: 'medicine_ball_slam', version: 1, name: 'Medicine-ball Slam', modality: 'strength', movementPatterns: ['hinge', 'upper_body_power'], primaryMuscles: ['lats', 'trunk', 'shoulders'], equipment: ['medicine_ball'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: [], instruction: 'Move explosively with complete control of the trunk and reset between repetitions.' },
  { id: 'front_squat', version: 1, name: 'Front Squat', modality: 'strength', movementPatterns: ['squat'], primaryMuscles: ['quadriceps', 'glutes', 'trunk'], equipment: ['barbell', 'rack'], impact: 'low', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'painful_deep_knee_flexion'], instruction: 'Use a controlled depth that preserves normal knee mechanics and leave several repetitions in reserve.' },
  { id: 'rear_foot_elevated_split_squat', version: 1, name: 'Rear-foot Elevated Split Squat', modality: 'strength', movementPatterns: ['unilateral_squat'], primaryMuscles: ['quadriceps', 'glutes', 'adductors'], equipment: ['dumbbells', 'bench'], impact: 'low', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'painful_deep_knee_flexion'], instruction: 'Use stable foot pressure and a symptom-free range. Do not chase fatigue.' },
  { id: 'romanian_deadlift', version: 1, name: 'Romanian Deadlift', modality: 'strength', movementPatterns: ['hinge'], primaryMuscles: ['hamstrings', 'glutes', 'back'], equipment: ['barbell'], impact: 'none', eccentricLoad: 'high', coordinationDemand: 'moderate', contraindicationTags: ['acute_hamstring_pain'], instruction: 'Use controlled eccentric tension without high-volume soreness before cycling quality.' },
  { id: 'bench_press', version: 1, name: 'Bench Press', modality: 'strength', movementPatterns: ['horizontal_push'], primaryMuscles: ['chest', 'triceps', 'shoulders'], equipment: ['barbell', 'bench', 'rack'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Use a stable setup and finish with two to four repetitions in reserve.' },
  { id: 'pull_up', version: 1, name: 'Pull-up', modality: 'strength', movementPatterns: ['vertical_pull'], primaryMuscles: ['lats', 'biceps', 'upper_back'], equipment: ['pullup_bar'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Use controlled full-range repetitions and avoid grinding.' },
  { id: 'band_pull_apart', version: 1, name: 'Band Pull-apart', modality: 'strength', movementPatterns: ['horizontal_abduction', 'shoulder_preparation'], primaryMuscles: ['rear_delts', 'upper_back'], equipment: ['resistance_bands'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Keep the ribs down and separate the band without shrugging or forcing end range.' },
  { id: 'scapular_push_up', version: 1, name: 'Scapular Push-up', modality: 'strength', movementPatterns: ['scapular_protraction', 'shoulder_preparation'], primaryMuscles: ['serratus_anterior', 'trunk'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Keep the elbows straight and move only through the shoulder blades with quiet ribs.' },
  { id: 'band_external_rotation', version: 1, name: 'Band External Rotation', modality: 'strength', movementPatterns: ['shoulder_external_rotation', 'shoulder_preparation'], primaryMuscles: ['rotator_cuff'], equipment: ['resistance_bands'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Keep the elbow comfortably at the side and rotate smoothly without compensating through the trunk.' },
  { id: 'dead_hang', version: 1, name: 'Dead Hang', modality: 'strength', movementPatterns: ['shoulder_preparation', 'grip'], primaryMuscles: ['lats', 'forearms'], equipment: ['pullup_bar'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Use an easy, pain-free hang or an active-shoulder variation; stop for shoulder discomfort or grip strain.' },
  { id: 'chest_supported_dumbbell_row', version: 1, name: 'Chest-supported Dumbbell Row', modality: 'strength', movementPatterns: ['horizontal_pull'], primaryMuscles: ['lats', 'upper_back', 'biceps'], equipment: ['dumbbells', 'bench'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Keep the chest on the bench, pull elbows toward the hips, pause briefly, and lower under control without loading the posterior chain.' },
  { id: 'seated_dumbbell_overhead_press', version: 1, name: 'Seated Dumbbell Overhead Press', modality: 'strength', movementPatterns: ['vertical_push'], primaryMuscles: ['shoulders', 'triceps'], equipment: ['dumbbells', 'bench'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Use back support, keep the feet relaxed and ribs down, and stop well before grinding.' },
  { id: 'rear_delt_raise', version: 1, name: 'Rear-delt Raise', modality: 'strength', movementPatterns: ['horizontal_abduction'], primaryMuscles: ['rear_delts', 'upper_back'], equipment: ['dumbbells', 'bench'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Use a light load, avoid shrugging, and move through a controlled pain-free range.' },
  { id: 'seated_soleus_iso', version: 1, name: 'Seated Soleus Isometric', modality: 'strength', movementPatterns: ['ankle_plantarflexion'], primaryMuscles: ['soleus'], equipment: ['bench'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['worsening_achilles_pain'], instruction: 'Hold a strong but comfortable contraction without increasing Achilles pain.' },
  { id: 'tibialis_raise', version: 1, name: 'Tibialis Raise', modality: 'strength', movementPatterns: ['ankle_dorsiflexion'], primaryMuscles: ['tibialis_anterior'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Lift the forefoot under control and avoid bouncing.' },
  { id: 'copenhagen_plank', version: 1, name: 'Copenhagen Plank', modality: 'strength', movementPatterns: ['adduction', 'anti_lateral_flexion'], primaryMuscles: ['adductors', 'obliques'], equipment: ['bench'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['acute_adductor_pain'], instruction: 'Maintain a straight trunk and stop before compensation.' },
  { id: 'pogo_hop', version: 1, name: 'Pogo Hop', modality: 'strength', movementPatterns: ['ankle_stiffness', 'reactive_jump'], primaryMuscles: ['calves', 'soleus'], equipment: ['bodyweight'], impact: 'high', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['worsening_achilles_pain', 'knee_swelling'], instruction: 'Use quiet, springy contacts with a stiff ankle. Stop if Achilles symptoms increase.' },
  { id: 'countermovement_jump', version: 1, name: 'Countermovement Jump', modality: 'strength', movementPatterns: ['jump', 'triple_extension'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bodyweight'], impact: 'high', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['worsening_achilles_pain', 'knee_swelling', 'painful_deep_knee_flexion'], instruction: 'Use a comfortable depth, land quietly, and reset fully between repetitions.' },
  { id: 'drop_jump_low', version: 1, name: 'Low Drop Jump', modality: 'strength', movementPatterns: ['reactive_jump', 'landing'], primaryMuscles: ['calves', 'quadriceps', 'glutes'], equipment: ['plyo_box'], impact: 'high', eccentricLoad: 'high', coordinationDemand: 'high', contraindicationTags: ['worsening_achilles_pain', 'knee_swelling', 'painful_deep_knee_flexion'], instruction: 'Step from a low box, land quietly and rebound only while mechanics remain crisp.' },
  { id: 'nordic_hamstring_curl', version: 1, name: 'Nordic Hamstring Curl', modality: 'strength', movementPatterns: ['knee_flexion', 'eccentric_hamstring'], primaryMuscles: ['hamstrings'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'high', coordinationDemand: 'moderate', contraindicationTags: ['acute_hamstring_pain'], instruction: 'Lower under control, use the hands to assist the return, and stop well before cramping or pain.' },
  { id: 'eccentric_heel_raise', version: 1, name: 'Eccentric Heel Raise', modality: 'strength', movementPatterns: ['ankle_plantarflexion', 'eccentric_calf'], primaryMuscles: ['soleus', 'gastrocnemius'], equipment: ['bodyweight'], impact: 'low', eccentricLoad: 'high', coordinationDemand: 'low', contraindicationTags: ['worsening_achilles_pain'], instruction: 'Rise with both feet if needed, lower slowly on one side, and keep symptoms at or below a mild stable level.' },
  { id: 'hip_thrust', version: 1, name: 'Hip Thrust', modality: 'strength', movementPatterns: ['hip_extension'], primaryMuscles: ['glutes', 'hamstrings'], equipment: ['barbell', 'bench'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['acute_hamstring_pain'], instruction: 'Brace the trunk, finish with the ribs down, and avoid lumbar hyperextension.' },
  { id: 'cable_chest_press', version: 1, name: 'Cable Chest Press', modality: 'strength', movementPatterns: ['horizontal_push'], primaryMuscles: ['chest', 'triceps', 'shoulders'], equipment: ['cable_machine'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Use a stable split stance and smooth, pain-free pressing range.' },
  { id: 'cable_row', version: 1, name: 'Cable Row', modality: 'strength', movementPatterns: ['horizontal_pull'], primaryMuscles: ['lats', 'upper_back', 'biceps'], equipment: ['cable_machine'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Keep the trunk quiet and finish each pull without shrugging.' },
  { id: 'field_dynamic_warmup', version: 1, name: 'Dynamic Field Warm-up', modality: 'field', movementPatterns: ['running', 'mobility'], primaryMuscles: ['calves', 'hamstrings', 'adductors'], equipment: ['field', 'cones'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Build speed gradually and confirm normal knee, calf and Achilles response.' },
  { id: 'acceleration_10m', version: 1, name: '10 m Acceleration', modality: 'field', movementPatterns: ['acceleration'], primaryMuscles: ['glutes', 'hamstrings', 'calves'], equipment: ['field', 'cones'], impact: 'moderate', eccentricLoad: 'low', coordinationDemand: 'high', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Accelerate smoothly rather than maximally and finish balanced.' },
  { id: 'controlled_deceleration', version: 1, name: 'Controlled Deceleration', modality: 'field', movementPatterns: ['braking'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['field', 'cones'], impact: 'moderate', eccentricLoad: 'high', coordinationDemand: 'high', contraindicationTags: ['knee_swelling', 'painful_braking'], instruction: 'Use several planned steps to reduce speed while keeping knee alignment controlled.' },
  { id: 'change_of_direction_45', version: 1, name: '45-degree Change of Direction', modality: 'field', movementPatterns: ['cutting', 'braking', 'acceleration'], primaryMuscles: ['quadriceps', 'glutes', 'adductors', 'calves'], equipment: ['field', 'cones'], impact: 'moderate', eccentricLoad: 'high', coordinationDemand: 'high', contraindicationTags: ['knee_swelling', 'instability', 'worsening_achilles_pain'], instruction: 'Use pre-planned cuts at controlled speed. Quality and tissue response matter more than volume.' },
  { id: 'ball_dribbling', version: 1, name: 'Ball Dribbling', modality: 'field', movementPatterns: ['running', 'skill'], primaryMuscles: ['calves', 'adductors', 'hip_flexors'], equipment: ['field', 'cones', 'football'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'high', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Keep the drill playful and technically clean without chaotic fatigue.' },
  { id: 'mobility_flow', version: 1, name: 'Mobility Flow', modality: 'mobility', movementPatterns: ['mobility', 'breathing'], primaryMuscles: ['hips', 'thoracic_spine', 'shoulders'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Use calm breathing and symptom-free ranges. This should reduce rather than create fatigue.' },
  { id: 'breathwork_downregulation', version: 1, name: 'Breathwork Downregulation', modality: 'mobility', movementPatterns: ['breathing', 'downregulation'], primaryMuscles: ['diaphragm'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Use a relaxed nasal inhale and longer easy exhale; stop if breath holding causes discomfort or dizziness.' },
  { id: 'aerobic_machine_easy', version: 1, name: 'Generic Aerobic Machine', modality: 'cross_training', movementPatterns: ['cyclical'], primaryMuscles: ['whole_body'], equipment: ['hotel_gym'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_knee_pain'], instruction: 'Use any available bike, elliptical, rower, SkiErg or similar machine by RPE and breathing, not by transferred watt targets.' },
  { id: 'walk_run_easy', version: 1, name: 'Easy Walk-run', modality: 'running', movementPatterns: ['walking', 'running'], primaryMuscles: ['calves', 'hamstrings', 'quadriceps'], equipment: [], impact: 'moderate', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Use a flat predictable route, quiet stride and easy conversational effort. Running time is optional and adjustable.' },
  { id: 'easy_continuous_run', version: 1, name: 'Easy Continuous Run', modality: 'running', movementPatterns: ['running', 'cyclical'], primaryMuscles: ['calves', 'hamstrings', 'quadriceps'], equipment: [], impact: 'moderate', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Keep a relaxed conversational pace on a flat, predictable route; stop and walk if mechanics or symptoms worsen.' },
  { id: 'goblet_squat', version: 1, name: 'Goblet Squat', modality: 'strength', movementPatterns: ['squat'], primaryMuscles: ['quadriceps', 'glutes', 'trunk'], equipment: ['dumbbells'], impact: 'low', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['knee_swelling', 'painful_deep_knee_flexion'], instruction: 'Use a comfortable depth and stop well before grinding.' },
  { id: 'dumbbell_row', version: 1, name: 'Dumbbell Row', modality: 'strength', movementPatterns: ['horizontal_pull'], primaryMuscles: ['lats', 'upper_back', 'biceps'], equipment: ['dumbbells'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Use a stable trunk and controlled range with several repetitions in reserve.' },
  { id: 'push_up', version: 1, name: 'Push-up', modality: 'strength', movementPatterns: ['horizontal_push'], primaryMuscles: ['chest', 'triceps', 'shoulders'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Choose an incline or floor version that stays smooth and leaves several repetitions in reserve.' },
  { id: 'dead_bug', version: 1, name: 'Dead Bug', modality: 'strength', movementPatterns: ['anti_extension', 'trunk_control'], primaryMuscles: ['trunk'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: [], instruction: 'Maintain quiet ribs and pelvis while moving slowly through a controlled range.' },
  { id: 'complete_rest_protocol', version: 1, name: 'Complete Rest', modality: 'recovery', movementPatterns: ['rest'], primaryMuscles: [], equipment: [], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Do not add training. Prioritize sleep, food, hydration and ordinary easy movement only.' },
  { id: 'sprint_wall_drive', version: 1, name: 'Sprint Wall Drive', modality: 'field', movementPatterns: ['acceleration', 'triple_extension'], primaryMuscles: ['glutes', 'hamstrings', 'calves'], equipment: ['field'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['acute_hamstring_pain', 'worsening_achilles_pain'], instruction: 'Keep a straight line from head through heel and drive the knee without arching the back.' },
  { id: 'sprint_a_march', version: 1, name: 'A-march', modality: 'field', movementPatterns: ['running', 'rhythm'], primaryMuscles: ['hip_flexors', 'calves', 'glutes'], equipment: ['field'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['worsening_achilles_pain'], instruction: 'March tall with a dorsiflexed ankle; strike beneath the hips rather than reaching forward.' },
  { id: 'sprint_falling_start_10m', version: 1, name: 'Falling-start 10 m', modality: 'field', movementPatterns: ['acceleration'], primaryMuscles: ['glutes', 'hamstrings', 'calves'], equipment: ['field', 'cones'], impact: 'moderate', eccentricLoad: 'low', coordinationDemand: 'high', contraindicationTags: ['acute_hamstring_pain', 'worsening_achilles_pain', 'knee_swelling'], instruction: 'Fall as one unit, push the ground back, and stop while the first steps remain crisp.' },
  { id: 'sprint_fly_10m', version: 1, name: 'Fly 10 m', modality: 'field', movementPatterns: ['max_velocity'], primaryMuscles: ['hamstrings', 'calves', 'hip_flexors'], equipment: ['field', 'cones'], impact: 'high', eccentricLoad: 'moderate', coordinationDemand: 'high', contraindicationTags: ['acute_hamstring_pain', 'worsening_achilles_pain', 'knee_swelling'], instruction: 'Build gradually, run tall and elastic through the fly zone, and end the repetition before form deteriorates.' },
  { id: 'deceleration_stick', version: 1, name: 'Deceleration Stick', modality: 'field', movementPatterns: ['braking'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['field', 'cones'], impact: 'moderate', eccentricLoad: 'high', coordinationDemand: 'high', contraindicationTags: ['knee_swelling', 'painful_braking'], instruction: 'Lower the centre of mass over several steps and finish balanced for two seconds.' },
  { id: 'bike_cadence_ladder', version: 1, name: 'Cadence Ladder', modality: 'cycling', movementPatterns: ['cyclical', 'rhythm'], primaryMuscles: ['hip_flexors', 'quadriceps', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Increase cadence in small steps while the pelvis stays quiet and breathing remains easy.' },
  { id: 'bike_spin_up', version: 1, name: 'Controlled Spin-up', modality: 'cycling', movementPatterns: ['cyclical', 'cadence'], primaryMuscles: ['hip_flexors', 'quadriceps', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'high', contraindicationTags: ['acute_knee_pain'], instruction: 'Spin smoothly to the highest cadence you can control; stop before bouncing or gripping the bars.' },
  { id: 'bike_seated_standing_transition', version: 1, name: 'Seated-to-standing Transition', modality: 'cycling', movementPatterns: ['cyclical', 'position_change'], primaryMuscles: ['quadriceps', 'glutes', 'trunk'], equipment: ['bike'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Change position with light hands and steady pressure; do not surge the gear to force the movement.' },
  { id: 'bike_braking_modulation', version: 1, name: 'Braking Modulation', modality: 'cycling', movementPatterns: ['braking', 'handling'], primaryMuscles: ['forearms', 'trunk'], equipment: ['bike', 'safe_riding_area'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'high', contraindicationTags: [], instruction: 'Practise progressive braking in a traffic-free area with eyes up and a straight predictable line.' },
  { id: 'bike_cornering_line', version: 1, name: 'Cornering Line', modality: 'cycling', movementPatterns: ['handling', 'cornering'], primaryMuscles: ['trunk', 'forearms'], equipment: ['bike', 'safe_riding_area'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'high', contraindicationTags: [], instruction: 'Look through the exit, brake before the turn, and use a conservative line at easy speed.' }
  ,{ id: 'run_tempo_interval', version: 1, name: 'Tempo Run Interval', modality: 'running', movementPatterns: ['running', 'sustained_pace'], primaryMuscles: ['calves', 'hamstrings', 'quadriceps'], equipment: [], impact: 'moderate', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Run smoothly at a controlled sustainable pace; do not chase a race effort.' }
  ,{ id: 'run_vo2_interval', version: 1, name: 'VO2 Run Interval', modality: 'running', movementPatterns: ['running', 'high_aerobic_power'], primaryMuscles: ['calves', 'hamstrings', 'quadriceps'], equipment: [], impact: 'high', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['acute_hamstring_pain', 'worsening_achilles_pain', 'knee_swelling'], instruction: 'Run hard but repeatably; stop the set if form or landing mechanics change.' }
  ,{ id: 'running_hill_repeat', version: 1, name: 'Running Hill Repeat', modality: 'running', movementPatterns: ['running', 'incline'], primaryMuscles: ['glutes', 'calves', 'hamstrings'], equipment: [], impact: 'moderate', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['acute_hamstring_pain', 'worsening_achilles_pain', 'knee_swelling'], instruction: 'Use a moderate hill and short quick steps; walk down fully before the next repetition.' }
  ,{ id: 'back_squat', version: 1, name: 'Back Squat', modality: 'strength', movementPatterns: ['squat'], primaryMuscles: ['quadriceps', 'glutes', 'trunk'], equipment: ['barbell', 'rack'], impact: 'low', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'painful_deep_knee_flexion'], instruction: 'Use a technically sound depth, a stable brace and no grinding.', facets: { family: 'strength', variant: 'back_squat', allowedDoseKinds: ['repetition'], allowedLoadKinds: ['mass', 'percent_one_rm', 'descriptive'], allowedLaterality: ['bilateral'], measurementProfile: 'repetitions', tissueDemand: ['knee_extensor', 'hip_extensor'], safetyTags: ['knee_swelling', 'painful_deep_knee_flexion'] } }
  ,{ id: 'power_clean_from_floor', version: 1, name: 'Power Clean from Floor', modality: 'strength', movementPatterns: ['hinge', 'triple_extension', 'pull'], primaryMuscles: ['glutes', 'hamstrings', 'traps'], equipment: ['barbell'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'high', contraindicationTags: ['acute_knee_pain', 'reactive_achilles'], instruction: 'Start from a stable floor position and stop the set when the catch or bar path degrades.', facets: { family: 'strength', variant: 'floor_clean', allowedDoseKinds: ['repetition'], allowedLoadKinds: ['mass', 'percent_one_rm', 'descriptive'], allowedLaterality: ['bilateral'], measurementProfile: 'repetitions', tissueDemand: ['posterior_chain', 'knee_extensor'], safetyTags: ['acute_knee_pain', 'reactive_achilles'] } }
  ,{ id: 'side_plank', version: 1, name: 'Side Plank', modality: 'strength', movementPatterns: ['lateral_trunk_control'], primaryMuscles: ['trunk', 'obliques'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Keep a long line from shoulder to knee or foot and stop before compensating through the lower back.', facets: { family: 'strength', variant: 'isometric', allowedDoseKinds: ['duration'], allowedLoadKinds: ['bodyweight', 'unloaded'], allowedLaterality: ['per_side'], measurementProfile: 'duration', tissueDemand: ['lateral_trunk'] } }
  ,{ id: 'quad_set', version: 1, name: 'Quad Set', modality: 'recovery', movementPatterns: ['knee_extension_isometric'], primaryMuscles: ['quadriceps'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_knee_pain'], instruction: 'Use a gentle, comfortable contraction without escalating knee symptoms.', facets: { family: 'recovery', variant: 'isometric', allowedDoseKinds: ['duration'], allowedLoadKinds: ['bodyweight', 'unloaded'], allowedLaterality: ['bilateral'], measurementProfile: 'duration', tissueDemand: ['knee_extensor'], safetyTags: ['acute_knee_pain'] } }
  ,{ id: 'sprint_15m', version: 1, name: '15 m Sprint', modality: 'field', movementPatterns: ['acceleration'], primaryMuscles: ['glutes', 'hamstrings', 'calves'], equipment: ['field', 'cones'], impact: 'moderate', eccentricLoad: 'low', coordinationDemand: 'high', contraindicationTags: ['acute_hamstring_pain', 'worsening_achilles_pain', 'knee_swelling'], instruction: 'Accelerate smoothly and stop while the first steps remain crisp.', facets: { family: 'field_drill', variant: '15m', allowedDoseKinds: ['distance'], allowedLoadKinds: ['unloaded'], allowedLaterality: ['bilateral'], measurementProfile: 'timed_sprint', fieldDomains: ['acceleration'], tissueDemand: ['posterior_chain', 'calf'], safetyTags: ['acute_hamstring_pain', 'worsening_achilles_pain', 'knee_swelling'] } }
  ,{ id: 'pro_agility_5_10_5', version: 1, name: 'Pro-Agility Shuttle (5-10-5)', modality: 'field', movementPatterns: ['braking', 'cutting', 'acceleration'], primaryMuscles: ['quadriceps', 'glutes', 'adductors', 'calves'], equipment: ['field', 'cones'], impact: 'moderate', eccentricLoad: 'high', coordinationDemand: 'high', contraindicationTags: ['knee_swelling', 'painful_braking', 'worsening_achilles_pain'], instruction: 'Use clean, planned direction changes and stop if cutting mechanics or symptoms worsen.', facets: { family: 'field_drill', variant: '5_10_5', allowedDoseKinds: ['distance'], allowedLoadKinds: ['unloaded'], allowedLaterality: ['alternating'], measurementProfile: 'timed_sprint', fieldDomains: ['acceleration', 'braking', 'change_of_direction'], tissueDemand: ['knee_extensor', 'adductor', 'calf'], safetyTags: ['knee_swelling', 'painful_braking', 'worsening_achilles_pain'] } }
  ,{ id: 'sprint_30m_with_splits', version: 1, name: '30 m Sprint with Splits', modality: 'field', movementPatterns: ['acceleration', 'max_velocity'], primaryMuscles: ['glutes', 'hamstrings', 'calves'], equipment: ['field', 'cones'], impact: 'high', eccentricLoad: 'moderate', coordinationDemand: 'high', contraindicationTags: ['acute_hamstring_pain', 'worsening_achilles_pain', 'knee_swelling'], instruction: 'Use the declared start and timing protocol; end testing if mechanics deteriorate.', facets: { family: 'field_drill', variant: '30m_split_test', allowedDoseKinds: ['distance'], allowedLoadKinds: ['unloaded'], allowedLaterality: ['bilateral'], measurementProfile: 'timed_sprint', fieldDomains: ['acceleration', 'max_velocity'], tissueDemand: ['posterior_chain', 'calf'], safetyTags: ['acute_hamstring_pain', 'worsening_achilles_pain', 'knee_swelling'] } }
  ,{ id: 'bike_vo2_interval', version: 1, name: 'VO2 Cycling Interval', modality: 'cycling', movementPatterns: ['cyclical', 'high_aerobic_power'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Ride at high aerobic power (e.g. 30/15 or 3-5 min intervals) with consistent repeatability.' }
  ,{ id: 'bike_float_interval', version: 1, name: 'Cycling Float Interval', modality: 'cycling', movementPatterns: ['cyclical'], primaryMuscles: ['quadriceps', 'glutes'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_knee_pain'], instruction: 'Maintain active pedalling pressure during float intervals without coasting.' }
  ,{ id: 'bike_sweet_spot_interval', version: 1, name: 'Sweet Spot Interval', modality: 'cycling', movementPatterns: ['cyclical', 'sustained_power'], primaryMuscles: ['quadriceps', 'glutes'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_knee_pain'], instruction: 'Ride steadily between 88-94% FTP with controlled breathing and quiet upper body.' }
  ,{ id: 'bike_tempo_steady', version: 1, name: 'Tempo Steady-State Cycling', modality: 'cycling', movementPatterns: ['cyclical', 'sustained_power'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_knee_pain'], instruction: 'Ride at steady Zone 3 aerobic tempo with stable rhythm and low power spikes.' }
  ,{ id: 'bike_microbursts', version: 1, name: 'Cycling Micro-bursts', modality: 'cycling', movementPatterns: ['cyclical', 'acceleration', 'high_aerobic_power'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'high', contraindicationTags: ['acute_knee_pain'], instruction: 'Alternate high-power accelerations with short active recoveries (e.g. 15s on / 15s off).' }
  ,{ id: 'bike_high_torque_climbing', version: 1, name: 'High-Torque Low-Cadence Climbing', modality: 'cycling', movementPatterns: ['cyclical', 'force_production'], primaryMuscles: ['quadriceps', 'glutes'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Pedal at 50-60 RPM against solid resistance while keeping knee alignment and pelvic posture stable.' }
  ,{ id: 'bike_sprint_power', version: 1, name: 'Maximal Cycling Sprint', modality: 'cycling', movementPatterns: ['cyclical', 'acceleration', 'max_power'], primaryMuscles: ['quadriceps', 'glutes', 'calves', 'trunk'], equipment: ['bike', 'safe_riding_area'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'high', contraindicationTags: ['acute_knee_pain'], instruction: 'Produce maximum explosive power for 5-15 seconds in a safe traffic-free environment.' }
  ,{ id: 'bike_race_simulation', version: 1, name: 'Road Race Simulation', modality: 'cycling', movementPatterns: ['cyclical', 'sustained_power', 'acceleration'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'high', contraindicationTags: ['acute_knee_pain'], instruction: 'Simulate race demands with variable power, drafting economy, and race-response surges.' }
  ,{ id: 'bike_race_opener', version: 1, name: 'Race Opener Surge', modality: 'cycling', movementPatterns: ['cyclical', 'acceleration'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Perform short, crisp race-pace openers without accumulating fatigue.' }
  ,{ id: 'bike_cooldown', version: 1, name: 'Bike Cooldown', modality: 'cycling', movementPatterns: ['cyclical'], primaryMuscles: ['quadriceps', 'calves'], equipment: ['bike'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Gradually spin down power and heart rate at an easy conversational effort.' }
  ,{ id: 'running_strides', version: 1, name: 'Running Strides', modality: 'running', movementPatterns: ['running', 'acceleration'], primaryMuscles: ['calves', 'hamstrings', 'glutes'], equipment: [], impact: 'moderate', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['acute_hamstring_pain', 'worsening_achilles_pain'], instruction: 'Accelerate smoothly to ~90-95% speed over 60-100m, focusing on relaxed mechanics and tall posture.' }
  ,{ id: 'running_drills', version: 1, name: 'Running Technical Drills', modality: 'running', movementPatterns: ['running', 'rhythm', 'mobility'], primaryMuscles: ['calves', 'hip_flexors', 'glutes'], equipment: [], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['worsening_achilles_pain'], instruction: 'Perform high knees, butt kicks and A-skips with quick ground contact and tall posture.' }
  ,{ id: 'run_fartlek', version: 1, name: 'Fartlek Run', modality: 'running', movementPatterns: ['running', 'speed_play'], primaryMuscles: ['calves', 'hamstrings', 'quadriceps'], equipment: [], impact: 'moderate', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Alternate faster pickups with easy floating recoveries according to feel.' }
  ,{ id: 'run_long_steady', version: 1, name: 'Long Aerobic Run', modality: 'running', movementPatterns: ['running', 'cyclical'], primaryMuscles: ['calves', 'hamstrings', 'quadriceps', 'glutes'], equipment: [], impact: 'high', eccentricLoad: 'high', coordinationDemand: 'low', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Maintain continuous conversational Zone 2 running, monitoring fatigue and surface impact.' }
  ,{ id: 'single_leg_romanian_deadlift', version: 1, name: 'Single-leg Romanian Deadlift', modality: 'strength', movementPatterns: ['unilateral_hinge'], primaryMuscles: ['hamstrings', 'glutes', 'calves'], equipment: ['dumbbells'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'high', contraindicationTags: ['acute_hamstring_pain'], instruction: 'Hinge forward on a single leg with level hips, soft knee and long spine; avoid twisting.' }
  ,{ id: 'walking_lunge', version: 1, name: 'Walking Lunge', modality: 'strength', movementPatterns: ['unilateral_squat', 'lunge'], primaryMuscles: ['quadriceps', 'glutes', 'adductors'], equipment: ['dumbbells'], impact: 'low', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'painful_deep_knee_flexion'], instruction: 'Step forward into a balanced lunge, lightly touching the back knee, and step smoothly through.' }
  ,{ id: 'step_up', version: 1, name: 'Dumbbell Step-up', modality: 'strength', movementPatterns: ['unilateral_squat'], primaryMuscles: ['quadriceps', 'glutes'], equipment: ['dumbbells', 'bench'], impact: 'low', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'painful_deep_knee_flexion'], instruction: 'Drive through the lead foot on the box/bench with minimal push off the trailing leg.' }
  ,{ id: 'kettlebell_swing', version: 1, name: 'Kettlebell Swing', modality: 'strength', movementPatterns: ['hinge', 'posterior_chain_power'], primaryMuscles: ['glutes', 'hamstrings', 'trunk'], equipment: ['kettlebell'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['acute_hamstring_pain'], instruction: 'Snap the hips forward powerfully, keeping the bell floating with the arms relaxed.' }
  ,{ id: 'kettlebell_deadlift', version: 1, name: 'Kettlebell Deadlift', modality: 'strength', movementPatterns: ['hinge'], primaryMuscles: ['glutes', 'hamstrings', 'back'], equipment: ['kettlebell'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['acute_hamstring_pain'], instruction: 'Hinge at the hips, brace the core, and drive through the floor without spinal flexion.' }
  ,{ id: 'standing_calf_raise', version: 1, name: 'Standing Calf Raise', modality: 'strength', movementPatterns: ['ankle_plantarflexion'], primaryMuscles: ['gastrocnemius', 'soleus'], equipment: ['dumbbells', 'bodyweight'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['worsening_achilles_pain'], instruction: 'Rise onto the balls of the feet with a full contraction, pause briefly, and lower slowly.' }
  ,{ id: 'calf_isometric', version: 1, name: 'Calf Isometric Hold', modality: 'strength', movementPatterns: ['ankle_plantarflexion'], primaryMuscles: ['calves', 'soleus'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['worsening_achilles_pain'], instruction: 'Hold a stable isometric calf contraction with quiet alignment.' }
  ,{ id: 'adductor_squeeze_isometric', version: 1, name: 'Adductor Squeeze Isometric', modality: 'strength', movementPatterns: ['adduction'], primaryMuscles: ['adductors'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['acute_adductor_pain'], instruction: 'Squeeze a block, ball, or fists between knees with controlled pain-free tension.' }
  ,{ id: 'lat_pulldown', version: 1, name: 'Lat Pulldown', modality: 'strength', movementPatterns: ['vertical_pull'], primaryMuscles: ['lats', 'upper_back', 'biceps'], equipment: ['cable_machine'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Pull the bar toward the upper chest with upright posture and controlled return.' }
  ,{ id: 'face_pull', version: 1, name: 'Face Pull', modality: 'strength', movementPatterns: ['horizontal_pull', 'shoulder_external_rotation'], primaryMuscles: ['rear_delts', 'rotator_cuff', 'upper_back'], equipment: ['cable_machine', 'resistance_bands'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Pull towards the forehead, rotating hands backwards with thumbs pointing behind you.' }
  ,{ id: 'dumbbell_lateral_raise', version: 1, name: 'Dumbbell Lateral Raise', modality: 'strength', movementPatterns: ['shoulder_abduction'], primaryMuscles: ['shoulders'], equipment: ['dumbbells'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Raise arms slightly in front of the frontal plane (scaption) to shoulder height without shrugging.' }
  ,{ id: 'incline_dumbbell_press', version: 1, name: 'Incline Dumbbell Press', modality: 'strength', movementPatterns: ['horizontal_push', 'incline_push'], primaryMuscles: ['chest', 'shoulders', 'triceps'], equipment: ['dumbbells', 'bench'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Press dumbbells smoothly along the incline angle with stable feet and braced trunk.' }
  ,{ id: 'dip', version: 1, name: 'Parallel Bar Dip', modality: 'strength', movementPatterns: ['vertical_push'], primaryMuscles: ['triceps', 'chest', 'shoulders'], equipment: ['pullup_bar', 'bodyweight'], impact: 'none', eccentricLoad: 'moderate', coordinationDemand: 'moderate', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Lower under control to a comfortable shoulder depth and press up smoothly.' }
  ,{ id: 'dumbbell_bicep_curl', version: 1, name: 'Dumbbell Bicep Curl', modality: 'strength', movementPatterns: ['elbow_flexion'], primaryMuscles: ['biceps', 'forearms'], equipment: ['dumbbells'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Curl weights smoothly with locked elbows; avoid swinging the upper body.' }
  ,{ id: 'triceps_rope_pushdown', version: 1, name: 'Triceps Rope Pushdown', modality: 'strength', movementPatterns: ['elbow_extension'], primaryMuscles: ['triceps'], equipment: ['cable_machine'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Extend elbows fully while keeping upper arms pinned comfortably to the sides.' }
  ,{ id: 'pallof_press', version: 1, name: 'Pallof Press', modality: 'strength', movementPatterns: ['anti_rotation', 'trunk_control'], primaryMuscles: ['obliques', 'trunk'], equipment: ['cable_machine', 'resistance_bands'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Hold the handle at chest height and press straight forward, resisting rotational pull.' }
  ,{ id: 'bird_dog', version: 1, name: 'Bird Dog', modality: 'strength', movementPatterns: ['anti_rotation', 'posterior_chain'], primaryMuscles: ['glutes', 'trunk', 'back'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: [], instruction: 'Extend opposite arm and leg simultaneously while maintaining level hips and quiet spine.' }
  ,{ id: 'plank', version: 1, name: 'Front Plank', modality: 'strength', movementPatterns: ['anti_extension', 'trunk_control'], primaryMuscles: ['trunk'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Maintain a straight line from shoulders to heels with neutral pelvis.' }
  ,{ id: 'hanging_leg_raise', version: 1, name: 'Hanging Knee/Leg Raise', modality: 'strength', movementPatterns: ['trunk_flexion', 'grip'], primaryMuscles: ['trunk', 'hip_flexors', 'forearms'], equipment: ['pullup_bar'], impact: 'none', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['acute_shoulder_pain'], instruction: 'Hang with active shoulders and lift knees toward the chest without excessive swinging.' }
  ,{ id: 'box_jump', version: 1, name: 'Box Jump', modality: 'strength', movementPatterns: ['jump', 'triple_extension', 'landing'], primaryMuscles: ['quadriceps', 'glutes', 'calves'], equipment: ['plyo_box'], impact: 'moderate', eccentricLoad: 'low', coordinationDemand: 'moderate', contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], instruction: 'Jump explosively onto the box, landing softly in an athletic stance; step down carefully.' }
  ,{ id: 'skater_hop', version: 1, name: 'Lateral Skater Hop', modality: 'strength', movementPatterns: ['lateral_jump', 'unilateral_landing'], primaryMuscles: ['glutes', 'quadriceps', 'adductors', 'calves'], equipment: ['bodyweight'], impact: 'moderate', eccentricLoad: 'moderate', coordinationDemand: 'high', contraindicationTags: ['knee_swelling', 'instability', 'worsening_achilles_pain'], instruction: 'Push laterally from one foot to the other, absorbing landing quietly on a stable knee.' }
  ,{ id: 'hip_90_90_mobility', version: 1, name: '90/90 Hip Flow', modality: 'mobility', movementPatterns: ['hip_mobility'], primaryMuscles: ['hips', 'glutes'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Transition smoothly between 90/90 hip angles, breathing calmly into tight areas.' }
  ,{ id: 'worlds_greatest_stretch', version: 1, name: "World's Greatest Stretch", modality: 'mobility', movementPatterns: ['lunge', 'thoracic_mobility', 'hip_mobility'], primaryMuscles: ['hip_flexors', 'thoracic_spine', 'hamstrings'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: [], instruction: 'Step into a deep lunge, place elbow inside ankle, and rotate open toward the sky.' }
  ,{ id: 'thoracic_open_book', version: 1, name: 'Thoracic Open Book', modality: 'mobility', movementPatterns: ['thoracic_mobility'], primaryMuscles: ['thoracic_spine', 'chest'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Lie on side with knees bent; rotate the top arm and chest across without hips moving.' }
  ,{ id: 'couch_stretch', version: 1, name: 'Couch Stretch (Hip Flexor)', modality: 'mobility', movementPatterns: ['hip_extension_mobility'], primaryMuscles: ['quadriceps', 'hip_flexors'], equipment: ['bodyweight', 'bench'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: ['painful_deep_knee_flexion'], instruction: 'Position back foot on bench/wall, tall kneeling posture, squeezing glute on the stretched side.' }
  ,{ id: 'cat_cow', version: 1, name: 'Cat-Cow Spine Flow', modality: 'mobility', movementPatterns: ['spinal_articulation', 'breathing'], primaryMuscles: ['trunk', 'back'], equipment: ['bodyweight'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'In quadruped, slowly articulate spine through flexion and extension synchronized with breath.' }
  ,{ id: 'foam_rolling_lower_body', version: 1, name: 'Lower Body Foam Rolling', modality: 'recovery', movementPatterns: ['soft_tissue_preparation'], primaryMuscles: ['quadriceps', 'calves', 'glutes'], equipment: ['foam_roller'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Roll calves, quads and glutes with slow, relaxed breathing to promote blood flow.' }
  ,{ id: 'active_recovery_walk', version: 1, name: 'Active Recovery Walk', modality: 'recovery', movementPatterns: ['walking'], primaryMuscles: ['calves', 'quadriceps'], equipment: [], impact: 'low', eccentricLoad: 'none', coordinationDemand: 'low', contraindicationTags: [], instruction: 'Walk at an easy leisurely pace to encourage lymphatic flow and recovery.' }
  ,{ id: 'rower_interval', version: 1, name: 'Rowing Machine Interval', modality: 'cross_training', movementPatterns: ['cyclical', 'high_aerobic_power', 'pull'], primaryMuscles: ['legs', 'back', 'lats'], equipment: ['hotel_gym'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: ['acute_knee_pain'], instruction: 'Drive with legs, swing hips, and pull handle to sternum repeatably during work intervals.' }
  ,{ id: 'skierg_interval', version: 1, name: 'SkiErg Interval', modality: 'cross_training', movementPatterns: ['cyclical', 'upper_body_power'], primaryMuscles: ['lats', 'trunk', 'shoulders'], equipment: ['hotel_gym'], impact: 'none', eccentricLoad: 'none', coordinationDemand: 'moderate', contraindicationTags: [], instruction: 'Hinge and pull down powerfully with arms and core, maintaining crisp rhythm.' }
];
