import type { WorkoutDefinition } from '../models.ts';
import { timeStep } from './helpers.ts';

const runningWarmup = (id: string) => timeStep(`${id}_warmup`, 'walk_run_easy', 'Easy running warm-up', 600, { target: { type: 'rpe', min: 2, max: 3 } });
const runningCooldown = (id: string) => timeStep(`${id}_cooldown`, 'walk_run_easy', 'Easy running cool-down', 600, { target: { type: 'rpe', min: 1, max: 2 } });

export const QUALITY_SUPPORT_WORKOUTS: WorkoutDefinition[] = [
  {
    id: 'running_tempo_01', version: 1, status: 'active', name: 'Steady Tempo Run', description: 'Controlled continuous tempo running that builds aerobic capacity without becoming a maximal effort.',
    modality: 'running', category: 'threshold', objectives: ['lactate_threshold', 'aerobic_base'], duration: { defaultMin: 40, minimumMin: 30, maximumMin: 55 }, loadProfile: { cardiovascular: 3, muscular: 3, mechanical: 3, eccentric: 3, coordination: 2, recoveryHours: 30 }, eligibility: { minimumReadiness: 6, maximumSoreness: 5, forbiddenPainFlags: ['knee_swelling', 'worsening_achilles_pain'] }, equipment: [], contraindicationTags: ['knee_swelling', 'worsening_achilles_pain'], engineTemplateIds: ['end_mod_01'],
    blocks: [{ id: 'warmup', name: 'Warm-up', role: 'warmup', steps: [runningWarmup('tempo')] }, { id: 'main', name: 'Tempo work', role: 'main', steps: [timeStep('tempo_main', 'run_tempo_interval', 'Steady tempo run', 1200, { target: { type: 'rpe', min: 5, max: 6 }, notes: ['Keep stride quiet and sustainable.'] })] }, { id: 'cooldown', name: 'Cool-down', role: 'cooldown', steps: [runningCooldown('tempo')] }],
    variants: [{ id: 'full', targetDurationMin: 40, loadMultiplier: 1, rationale: 'Full controlled tempo exposure.', stepOverrides: [] }, { id: 'reduced', targetDurationMin: 35, loadMultiplier: 0.75, rationale: 'Shorten the continuous work.', stepOverrides: [{ stepId: 'tempo_main', durationSeconds: 900 }] }, { id: 'return_to_training', targetDurationMin: 30, loadMultiplier: 0.55, rationale: 'Use a short easy-to-steady exposure.', stepOverrides: [{ stepId: 'tempo_main', durationSeconds: 600, target: { type: 'rpe', min: 3, max: 4 } }] }],
    regressions: ['running_walk_run_01'], progressions: ['running_vo2_4x4_01'], substitutions: [], garmin: { exportable: true, supportedSport: 'running' }, tags: ['running', 'tempo', 'quality'], sourceNotes: ['Matches the engine’s moderate running template with a genuine tempo prescription.']
  },
  {
    id: 'running_vo2_4x4_01', version: 1, status: 'active', name: 'Running VO2 Intervals 4×4', description: 'Repeatable high-aerobic running intervals with enough recovery to protect running mechanics.',
    modality: 'running', category: 'threshold', objectives: ['high_aerobic_power'], duration: { defaultMin: 45, minimumMin: 32, maximumMin: 60 }, loadProfile: { cardiovascular: 5, muscular: 4, mechanical: 4, eccentric: 3, coordination: 3, recoveryHours: 48 }, eligibility: { minimumReadiness: 7, maximumSoreness: 4, minimumDaysAfterHardLowerBody: 1, forbiddenPainFlags: ['acute_hamstring_pain', 'knee_swelling', 'worsening_achilles_pain'] }, equipment: [], contraindicationTags: ['acute_hamstring_pain', 'knee_swelling', 'worsening_achilles_pain'], engineTemplateIds: ['end_hard_01'],
    blocks: [{ id: 'warmup', name: 'Warm-up', role: 'warmup', steps: [runningWarmup('vo2')] }, { id: 'main', name: 'VO2 intervals', role: 'main', steps: [timeStep('vo2_main', 'run_vo2_interval', '4-minute VO2 interval', 240, { sets: 4, restAfterSec: 180, target: { type: 'rpe', min: 8, max: 9 }, notes: ['Walk or jog recovery; stop if landing mechanics change.'] })] }, { id: 'cooldown', name: 'Cool-down', role: 'cooldown', steps: [runningCooldown('vo2')] }],
    variants: [{ id: 'full', targetDurationMin: 45, loadMultiplier: 1, rationale: 'Four repeatable hard intervals.', stepOverrides: [] }, { id: 'reduced', targetDurationMin: 38, loadMultiplier: 0.75, rationale: 'Reduce interval count before increasing effort.', stepOverrides: [{ stepId: 'vo2_main', sets: 3 }] }, { id: 'return_to_training', targetDurationMin: 32, loadMultiplier: 0.55, rationale: 'Use shorter controlled efforts.', stepOverrides: [{ stepId: 'vo2_main', sets: 3, durationSeconds: 180, target: { type: 'rpe', min: 6, max: 7 } }] }],
    regressions: ['running_tempo_01'], progressions: [], substitutions: [], garmin: { exportable: true, supportedSport: 'running' }, tags: ['running', 'vo2', 'quality'], sourceNotes: ['Matches the engine’s 4×4 running interval template.']
  },
  {
    id: 'running_hill_repeats_01', version: 1, status: 'active', name: 'Running Hill Repeats', description: 'Short controlled hill repetitions with walk-down recovery and no sprint finish.',
    modality: 'running', category: 'surge_tolerance', objectives: ['high_aerobic_power', 'running_exposure'], duration: { defaultMin: 35, minimumMin: 28, maximumMin: 55 }, loadProfile: { cardiovascular: 4, muscular: 4, mechanical: 3, eccentric: 2, coordination: 3, recoveryHours: 42 }, eligibility: { minimumReadiness: 7, maximumSoreness: 4, forbiddenPainFlags: ['acute_hamstring_pain', 'knee_swelling', 'worsening_achilles_pain'] }, equipment: [], contraindicationTags: ['acute_hamstring_pain', 'knee_swelling', 'worsening_achilles_pain'], engineTemplateIds: ['end_hard_03'],
    blocks: [{ id: 'warmup', name: 'Warm-up', role: 'warmup', steps: [runningWarmup('hill')] }, { id: 'main', name: 'Hill repetitions', role: 'main', steps: [timeStep('hill_main', 'running_hill_repeat', 'Hill repeat', 60, { sets: 6, restAfterSec: 90, target: { type: 'rpe', min: 7, max: 8 } })] }, { id: 'cooldown', name: 'Cool-down', role: 'cooldown', steps: [runningCooldown('hill')] }],
    variants: [{ id: 'full', targetDurationMin: 35, loadMultiplier: 1, rationale: 'Six controlled hill repetitions.', stepOverrides: [] }, { id: 'reduced', targetDurationMin: 30, loadMultiplier: 0.7, rationale: 'Reduce contacts and preserve the hill technique.', stepOverrides: [{ stepId: 'hill_main', sets: 4 }] }, { id: 'return_to_training', targetDurationMin: 28, loadMultiplier: 0.5, rationale: 'Use easy uphill strides rather than hard repeats.', stepOverrides: [{ stepId: 'hill_main', sets: 3, target: { type: 'rpe', min: 4, max: 5 } }] }],
    regressions: ['running_tempo_01'], progressions: [], substitutions: [], garmin: { exportable: true, supportedSport: 'running' }, tags: ['running', 'hills', 'quality'], sourceNotes: ['Matches the engine’s hill-repeat template rather than falling back to walk-run.']
  },
  {
    id: 'cycling_tempo_surges_01', version: 1, status: 'active', name: 'Cycling Tempo with Controlled Surges', description: 'Steady tempo cycling with modest surges, distinct from threshold intervals.',
    modality: 'cycling', category: 'threshold', objectives: ['aerobic_base', 'surge_tolerance'], duration: { defaultMin: 40, minimumMin: 30, maximumMin: 75 }, loadProfile: { cardiovascular: 3, muscular: 3, mechanical: 1, eccentric: 1, coordination: 2, recoveryHours: 30 }, eligibility: { minimumReadiness: 5, maximumSoreness: 6, forbiddenPainFlags: ['acute_knee_pain'] }, equipment: ['bike'], contraindicationTags: ['acute_knee_pain'], engineTemplateIds: ['end_mod_02'],
    blocks: [{ id: 'warmup', name: 'Warm-up', role: 'warmup', steps: [timeStep('tempo_bike_warmup', 'bike_progressive_warmup', 'Progressive warm-up', 600, { targets: [{ role: 'fallback', metric: 'rpe', value: { min: 1, max: 3 } }] })] }, { id: 'main', name: 'Tempo ride', role: 'main', steps: [timeStep('tempo_bike_main', 'bike_threshold_interval', 'Steady tempo ride', 1200, { targets: [{ role: 'primary', metric: 'ftp_percent', value: { min: 76, max: 90 }, requires: 'power_meter' }, { role: 'fallback', metric: 'rpe', value: { min: 5, max: 6 } }, { role: 'secondary', metric: 'heart_rate_zone', value: { zone: 3 }, requires: 'heart_rate_monitor' }], notes: ['Include only brief controlled cadence changes; stay below threshold.'] })] }, { id: 'cooldown', name: 'Cool-down', role: 'cooldown', steps: [timeStep('tempo_bike_cooldown', 'bike_easy_spin', 'Easy spin', 600, { targets: [{ role: 'fallback', metric: 'rpe', value: { min: 1, max: 2 } }] })] }],
    variants: [{ id: 'full', targetDurationMin: 40, loadMultiplier: 1, rationale: 'Full controlled tempo ride.', stepOverrides: [] }, { id: 'reduced', targetDurationMin: 35, loadMultiplier: 0.75, rationale: 'Shorten the steady tempo work.', stepOverrides: [{ stepId: 'tempo_bike_main', durationSeconds: 900 }] }, { id: 'return_to_training', targetDurationMin: 30, loadMultiplier: 0.55, rationale: 'Use an easy-to-steady ride.', stepOverrides: [{ stepId: 'tempo_bike_main', durationSeconds: 600, target: { type: 'rpe', min: 3, max: 4 } }] }],
    regressions: ['cycling_zone2_standard_01'], progressions: ['cycling_controlled_threshold_4x8_01'], substitutions: [], garmin: { exportable: true, supportedSport: 'cycling' }, tags: ['cycling', 'tempo', 'quality'], sourceNotes: ['Matches the engine’s cycling tempo template rather than substituting threshold intervals.']
  },
  {
    id: 'cycling_vo2_6x3_01', version: 1, status: 'active', name: 'Cycling VO2 Intervals 6×3', description: 'Six repeatable three-minute high-aerobic cycling efforts with equal recovery.',
    modality: 'cycling', category: 'threshold', objectives: ['high_aerobic_power'], duration: { defaultMin: 45, minimumMin: 35, maximumMin: 65 }, loadProfile: { cardiovascular: 5, muscular: 4, mechanical: 1, eccentric: 1, coordination: 3, recoveryHours: 48 }, eligibility: { minimumReadiness: 7, maximumSoreness: 5, minimumDaysAfterHardLowerBody: 1, forbiddenPainFlags: ['acute_knee_pain'] }, equipment: ['bike'], contraindicationTags: ['acute_knee_pain'], engineTemplateIds: ['end_hard_02'],
    blocks: [{ id: 'warmup', name: 'Warm-up', role: 'warmup', steps: [timeStep('bike_vo2_warmup', 'bike_progressive_warmup', 'Progressive warm-up', 600, { target: { type: 'rpe', min: 1, max: 3 } })] }, { id: 'main', name: 'VO2 intervals', role: 'main', steps: [timeStep('bike_vo2_main', 'bike_threshold_interval', '3-minute VO2 interval', 180, { sets: 6, restAfterSec: 180, target: { type: 'rpe', min: 8, max: 9 } })] }, { id: 'cooldown', name: 'Cool-down', role: 'cooldown', steps: [timeStep('bike_vo2_cooldown', 'bike_easy_spin', 'Easy spin', 600, { target: { type: 'rpe', min: 1, max: 2 } })] }],
    variants: [{ id: 'full', targetDurationMin: 45, loadMultiplier: 1, rationale: 'Six repeatable VO2 efforts.', stepOverrides: [] }, { id: 'reduced', targetDurationMin: 39, loadMultiplier: 0.7, rationale: 'Reduce count while preserving interval quality.', stepOverrides: [{ stepId: 'bike_vo2_main', sets: 4 }] }, { id: 'return_to_training', targetDurationMin: 35, loadMultiplier: 0.5, rationale: 'Use short controlled high-aerobic work.', stepOverrides: [{ stepId: 'bike_vo2_main', sets: 3, target: { type: 'rpe', min: 6, max: 7 } }] }],
    regressions: ['cycling_tempo_surges_01'], progressions: ['cycling_over_under_3x12_01'], substitutions: [], garmin: { exportable: true, supportedSport: 'cycling' }, tags: ['cycling', 'vo2', 'quality'], sourceNotes: ['Matches the engine’s cycling 6×3 VO2 template.']
  },
  {
    id: 'cycling_vo2_variable_01', version: 1, status: 'active', name: 'Cycling Variable-intensity VO2 Intervals', description: 'Long variable-intensity efforts that accumulate high-aerobic work without a maximal final rep.',
    modality: 'cycling', category: 'threshold', objectives: ['high_aerobic_power', 'surge_tolerance'], duration: { defaultMin: 48, minimumMin: 35, maximumMin: 65 }, loadProfile: { cardiovascular: 5, muscular: 4, mechanical: 1, eccentric: 1, coordination: 3, recoveryHours: 48 }, eligibility: { minimumReadiness: 7, maximumSoreness: 5, minimumDaysAfterHardLowerBody: 1, forbiddenPainFlags: ['acute_knee_pain'] }, equipment: ['bike'], contraindicationTags: ['acute_knee_pain'], engineTemplateIds: ['end_hard_02'], engineTemplatePriority: 2,
    blocks: [{ id: 'warmup', name: 'Warm-up', role: 'warmup', steps: [timeStep('variable_warmup', 'bike_progressive_warmup', 'Progressive warm-up', 600, { target: { type: 'rpe', min: 1, max: 3 } })] }, { id: 'main', name: 'Variable VO2 work', role: 'main', steps: [timeStep('variable_vo2_main', 'bike_threshold_interval', 'Variable-intensity VO2 interval', 240, { sets: 4, restAfterSec: 180, target: { type: 'rpe', min: 8, max: 9 }, notes: ['Alternate 60 seconds controlled-hard with 60 seconds very hard; finish each rep repeatable.'] })] }, { id: 'cooldown', name: 'Cool-down', role: 'cooldown', steps: [timeStep('variable_cooldown', 'bike_easy_spin', 'Easy spin', 600, { target: { type: 'rpe', min: 1, max: 2 } })] }],
    variants: [{ id: 'full', targetDurationMin: 48, loadMultiplier: 1, rationale: 'Four variable-intensity high-aerobic repetitions.', stepOverrides: [] }, { id: 'reduced', targetDurationMin: 42, loadMultiplier: 0.7, rationale: 'Reduce repetition count while preserving recovery.', stepOverrides: [{ stepId: 'variable_vo2_main', sets: 3 }] }, { id: 'return_to_training', targetDurationMin: 35, loadMultiplier: 0.5, rationale: 'Use controlled high-aerobic efforts only.', stepOverrides: [{ stepId: 'variable_vo2_main', sets: 3, durationSeconds: 180, target: { type: 'rpe', min: 6, max: 7 } }] }],
    regressions: ['cycling_tempo_surges_01'], progressions: [], substitutions: [], garmin: { exportable: true, supportedSport: 'cycling' }, tags: ['cycling', 'vo2', 'variable_intensity'], sourceNotes: ['Uses longer variable-intensity work intervals to accumulate high-aerobic exposure.']
  },
  {
    id: 'cycling_vo2_short_30_15_01', version: 1, status: 'active', name: 'Cycling Short VO2 Intervals 30/15', description: 'Short on/off VO2 intervals with deliberately brief recoveries and controlled cadence.',
    modality: 'cycling', category: 'threshold', objectives: ['high_aerobic_power', 'surge_tolerance'], duration: { defaultMin: 42, minimumMin: 30, maximumMin: 55 }, loadProfile: { cardiovascular: 5, muscular: 3, mechanical: 1, eccentric: 1, coordination: 3, recoveryHours: 42 }, eligibility: { minimumReadiness: 7, maximumSoreness: 5, minimumDaysAfterHardLowerBody: 1, forbiddenPainFlags: ['acute_knee_pain'] }, equipment: ['bike'], contraindicationTags: ['acute_knee_pain'], engineTemplateIds: ['end_hard_02'], engineTemplatePriority: 3,
    blocks: [{ id: 'warmup', name: 'Warm-up', role: 'warmup', steps: [timeStep('short_warmup', 'bike_progressive_warmup', 'Progressive warm-up', 600, { target: { type: 'rpe', min: 1, max: 3 } })] }, { id: 'main', name: '30/15 intervals', role: 'main', steps: [timeStep('short_vo2_main', 'bike_threshold_interval', '30-second hard effort', 30, { sets: 20, restAfterSec: 15, target: { type: 'rpe', min: 8, max: 9 }, notes: ['Keep cadence controlled; end the set if power or form collapses.'] })] }, { id: 'cooldown', name: 'Cool-down', role: 'cooldown', steps: [timeStep('short_cooldown', 'bike_easy_spin', 'Easy spin', 600, { target: { type: 'rpe', min: 1, max: 2 } })] }],
    variants: [{ id: 'full', targetDurationMin: 42, loadMultiplier: 1, rationale: 'Twenty crisp 30/15 repetitions.', stepOverrides: [] }, { id: 'reduced', targetDurationMin: 35, loadMultiplier: 0.7, rationale: 'Reduce total short efforts.', stepOverrides: [{ stepId: 'short_vo2_main', sets: 14 }] }, { id: 'return_to_training', targetDurationMin: 30, loadMultiplier: 0.5, rationale: 'Use a short controlled set only.', stepOverrides: [{ stepId: 'short_vo2_main', sets: 10, target: { type: 'rpe', min: 6, max: 7 } }] }],
    regressions: ['cycling_tempo_surges_01'], progressions: [], substitutions: [], garmin: { exportable: true, supportedSport: 'cycling' }, tags: ['cycling', 'vo2', 'short_intervals'], sourceNotes: ['Short 30/15 work is a compact high-aerobic format when mechanics and knee response remain normal.']
  }
];
